// localizacoes.ts

export interface LocalizacaoEstrutura {
  [continente: string]: {
    [pais: string]: {
      [estado: string]: string[];
    };
  };
}

export const LOCALIZACAO_DATA: LocalizacaoEstrutura = {
  "América": {
    "Brasil": {
      "Acre": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"],
      "Alagoas": ["Maceió", "Arapiraca", "Palmeira dos Índios"],
      "Amapá": ["Macapá", "Santana", "Laranjal do Jari"],
      "Amazonas": ["Manaus", "Parintins", "Itacoatiara"],
      "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista"],
      "Ceará": ["Fortaleza", "Caucaia", "Juazeiro do Norte"],
      "Distrito Federal": ["Brasília"],
      "Espírito Santo": ["Vitória", "Vila Velha", "Serra", "Cariacica"],
      "Goiás": ["Goiânia", "Aparecida de Goiânia", "Anápolis"],
      "Maranhão": ["São Luís", "Imperatriz", "Timon"],
      "Mato Grosso": ["Cuiabá", "Várzea Grande", "Rondonópolis"],
      "Mato Grosso do Sul": ["Campo Grande", "Dourados", "Três Lagoas"],
      "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora"],
      "Pará": ["Belém", "Ananindeua", "Santarém"],
      "Paraíba": ["João Pessoa", "Campina Grande", "Patos"],
      "Paraná": ["Curitiba", "Londrina", "Maringá", "Cascavel"],
      "Pernambuco": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru"],
      "Piauí": ["Teresina", "Parnaíba", "Picos"],
      "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Duque de Caxias", "Belford Roxo", "São Gonçalo"],
      "Rio Grande do Norte": ["Natal", "Mossoró", "Parnamirim"],
      "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas"],
      "Rondônia": ["Porto Velho", "Ji-Paraná", "Ariquemes"],
      "Roraima": ["Boa Vista", "Rorainópolis", "Caracaraí"],
      "Santa Catarina": ["Florianópolis", "Joinville", "Blumenau", "Chapecó"],
      "São Paulo": ["São Paulo", "Campinas", "Santos", "São Bernardo do Campo", "São José dos Campos"],
      "Sergipe": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto"],
      "Tocantins": ["Palmas", "Araguaína", "Gurupi"]
    },
    "Estados Unidos": {
      "Califórnia": ["Los Angeles", "San Francisco", "San Diego"],
      "Nova York": ["Nova York", "Buffalo", "Rochester"],
      "Flórida": ["Miami", "Orlando", "Tampa"],
      "Texas": ["Houston", "Austin", "Dallas"]
    },
    "Canadá": {
      "Ontario": ["Toronto", "Ottawa"],
      "Quebec": ["Montreal", "Quebec City"],
      "British Columbia": ["Vancouver", "Victoria"]
    },
    "Argentina": { "Principal": ["Buenos Aires", "Córdoba", "Rosário"] },
    "México": { "Principal": ["Cidade do México", "Guadalajara", "Monterrey"] },
    "Colômbia": { "Principal": ["Bogotá", "Medellín", "Cali"] },
    "Chile": { "Principal": ["Santiago", "Valparaíso", "Concepción"] },
    "Peru": { "Principal": ["Lima", "Arequipa", "Trujillo"] },
    "Uruguai": { "Principal": ["Montevidéu", "Salto", "Maldonado"] },
    "Paraguai": { "Principal": ["Assunção", "Ciudad del Este"] },
    "Bolívia": { "Principal": ["La Paz", "Sucre", "Santa Cruz de la Sierra"] },
    "Equador": { "Principal": ["Quito", "Guayaquil"] },
    "Venezuela": { "Principal": ["Caracas", "Maracaibo"] },
    "Cuba": { "Principal": ["Havana"] },
    "Costa Rica": { "Principal": ["San José"] },
    "Panamá": { "Principal": ["Cidade do Panamá"] },
    "Guatemala": { "Principal": ["Cidade de Guatemala"] },
    "Honduras": { "Principal": ["Tegucigalpa"] },
    "El Salvador": { "Principal": ["San Salvador"] },
    "Nicarágua": { "Principal": ["Manágua"] },
    "República Dominicana": { "Principal": ["Santo Domingo"] },
    "Jamaica": { "Principal": ["Kingston"] },
    "Bahamas": { "Principal": ["Nassau"] }
  },
  "Europa": {
    "Portugal": {
      "Lisboa": ["Lisboa", "Sintra", "Cascais"],
      "Porto": ["Porto", "Vila Nova de Gaia", "Matosinhos"],
      "Braga": ["Braga", "Guimarães"]
    },
    "Reino Unido": { "Principal": ["Londres", "Manchester", "Birmingham", "Edinburgh", "Glasgow"] },
    "Alemanha": { "Principal": ["Berlim", "Munique", "Frankfurt", "Hamburgo", "Colônia"] },
    "França": { "Principal": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"] },
    "Itália": { "Principal": ["Roma", "Milão", "Nápoles", "Turim", "Florença"] },
    "Espanha": { "Principal": ["Madri", "Barcelona", "Valência", "Sevilha"] },
    "Irlanda": { "Principal": ["Dublin", "Cork", "Galway"] },
    "Holanda": { "Principal": ["Amsterdã", "Roterdã", "Utrecht"] },
    "Bélgica": { "Principal": ["Bruxelas", "Antuérpia", "Bruges"] },
    "Suíça": { "Principal": ["Zurique", "Genebra", "Berna"] },
    "Áustria": { "Principal": ["Viena", "Salzburgo"] },
    "Suécia": { "Principal": ["Estocolmo", "Gotemburgo"] },
    "Noruega": { "Principal": ["Oslo", "Bergen"] },
    "Dinamarca": { "Principal": ["Copenhague"] },
    "Finlândia": { "Principal": ["Helsinque"] },
    "Polônia": { "Principal": ["Varsóvia", "Cracóvia"] },
    "Grécia": { "Principal": ["Atenas", "Salônica"] },
    "Rússia": { "Principal": ["Moscou", "São Petersburgo"] },
    "Ucrânia": { "Principal": ["Kiev", "Lviv"] },
    "República Checa": { "Principal": ["Praga"] },
    "Hungria": { "Principal": ["Budapeste"] },
    "Romênia": { "Principal": ["Bucareste"] },
    "Bulgária": { "Principal": ["Sófia"] },
    "Croácia": { "Principal": ["Zagreb"] },
    "Albânia": { "Principal": ["Tirana"] },
    "Eslováquia": { "Principal": ["Bratislava"] },
    "Eslovênia": { "Principal": ["Liubliana"] },
    "Islândia": { "Principal": ["Reiquiavique"] },
    "Estônia": { "Principal": ["Tallinn"] },
    "Letônia": { "Principal": ["Riga"] },
    "Lituânia": { "Principal": ["Vilnius"] },
    "Luxemburgo": { "Principal": ["Cidade de Luxemburgo"] },
    "Malta": { "Principal": ["Valletta"] },
    "Mônaco": { "Principal": ["Mônaco"] }
  },
  "Ásia": {
    "Japão": { "Principal": ["Tóquio", "Quioto", "Osaka", "Yokohama"] },
    "China": { "Principal": ["Pequim", "Xangai", "Shenzhen", "Guangzhou"] },
    "Índia": { "Principal": ["Nova Deli", "Mumbai", "Bangalore", "Hyderabad"] },
    "Coreia do Sul": { "Principal": ["Seul", "Busan", "Incheon"] },
    "Israel": { "Principal": ["Tel Aviv", "Jerusalém", "Haifa"] },
    "Emirados Árabes Unidos": { "Principal": ["Dubai", "Abu Dhabi", "Sharjah"] },
    "Singapura": { "Principal": ["Singapura"] },
    "Tailândia": { "Principal": ["Bangcoc", "Phuket"] }, // Mantenha apenas esta com as cidades juntas
    "Indonésia": { "Principal": ["Jacarta", "Bali"] },
    "Filipinas": { "Principal": ["Manila"] },
    "Vietnã": { "Principal": ["Hanói", "Cidade de Ho Chi Minh"] },
    "Malásia": { "Principal": ["Kuala Lumpur"] },
    "Paquistão": { "Principal": ["Islamabad", "Karachi"] },
    "Bangladesh": { "Principal": ["Daca"] },
    "Arábia Saudita": { "Principal": ["Riade", "Jedá"] },
    "Turquia": { "Principal": ["Istambul", "Ancara", "Izmir"] },
    "Irã": { "Principal": ["Teerã"] },
    "Iraque": { "Principal": ["Bagdá"] },
    "Catar": { "Principal": ["Doha"] },
    "Líbano": { "Principal": ["Beirute"] },
    "Taiwan": { "Principal": ["Taipé"] },
    "Cazaquistão": { "Principal": ["Astana"] },
    "Uzbequistão": { "Principal": ["Tashkent"] },
    "Sri Lanka": { "Principal": ["Colombo"] },
    "Nepal": { "Principal": ["Katmandu"] },
    "Maldivas": { "Principal": ["Malé"] }
  },
  "África": {
    "África do Sul": { "Principal": ["Cidade do Cabo", "Joanesburgo", "Pretória"] },
    "Angola": { "Principal": ["Luanda", "Benguela", "Huambo"] },
    "Moçambique": { "Principal": ["Maputo", "Beira", "Nampula"] },
    "Egito": { "Principal": ["Cairo", "Alexandria", "Gizé"] },
    "Marrocos": { "Principal": ["Rabat", "Casablanca", "Marraquexe"] },
    "Nigéria": { "Principal": ["Abuja", "Lagos"] },
    "Quênia": { "Principal": ["Nairobi", "Mombasa"] },
    "Gana": { "Principal": ["Acra"] },
    "Etiópia": { "Principal": ["Adis Abeba"] },
    "Argélia": { "Principal": ["Argel"] },
    "Tunísia": { "Principal": ["Túnis"] },
    "Cabo Verde": { "Principal": ["Praia", "Mindelo"] },
    "Guiné-Bissau": { "Principal": ["Bissau"] },
    "São Tomé e Príncipe": { "Principal": ["São Tomé"] },
    "Senegal": { "Principal": ["Dakar"] },
    "Camarões": { "Principal": ["Yaoundé", "Douala"] },
    "Costa do Marfim": { "Principal": ["Abidjan", "Yamoussoukro"] },
    "Madagascar": { "Principal": ["Antananarivo"] },
    "Uganda": { "Principal": ["Kampala"] },
    "Tanzânia": { "Principal": ["Dodoma", "Dar es Salaam"] },
    "Sudão": { "Principal": ["Cartum"] },
    "Líbia": { "Principal": ["Trípoli"] }
  },
  "Oceania": {
    "Austrália": { "Principal": ["Sydney", "Melbourne", "Brisbane", "Perth", "Canberra"] },
    "Nova Zelândia": { "Principal": ["Auckland", "Wellington", "Christchurch"] },
    "Fiji": { "Principal": ["Suva"] },
    "Papua Nova Guiné": { "Principal": ["Port Moresby"] },
    "Samoa": { "Principal": ["Apia"] },
    "Tonga": { "Principal": ["Nuku'alofa"] }
  }
};